"""favourites

Revision ID: 314d13f1a3cf
Revises: 839458d947c5
Create Date: 2020-05-15 21:59:26.989144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314d13f1a3cf'
down_revision = '839458d947c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.Column('date_death', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('author_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('ISBN', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('book_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], )
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_ISBN', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_timestamp'), 'feedback', ['timestamp'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_feedback_timestamp'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('favourites')
    op.drop_table('authors')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
