"""empty message

Revision ID: 43951bf82b32
Revises: edf18334d4f9
Create Date: 2020-05-20 13:45:29.010606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43951bf82b32'
down_revision = 'edf18334d4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'image')
    # ### end Alembic commands ###
