"""publishers + editions

Revision ID: aa4b1d44349c
Revises: edf18334d4f9
Create Date: 2020-05-20 15:24:51.955667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4b1d44349c'
down_revision = 'edf18334d4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('URL', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('book_ISBN', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('author', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'image')
    op.drop_table('edition')
    op.drop_table('publisher')
    # ### end Alembic commands ###
