"""book_title_reserved + to feedback

Revision ID: cab5f4843cc1
Revises: 0f3276312f72
Create Date: 2020-05-21 13:23:34.700474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab5f4843cc1'
down_revision = '0f3276312f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('book_title_reserved', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'book_title_reserved')
    # ### end Alembic commands ###
