"""empty message

Revision ID: edf18334d4f9
Revises: e5a36e655e4b
Create Date: 2020-05-18 18:58:47.444558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf18334d4f9'
down_revision = 'e5a36e655e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('genre')
    # ### end Alembic commands ###
