"""add indexes

Revision ID: f8671d302eae
Revises: cab5f4843cc1
Create Date: 2020-05-21 21:54:58.917931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8671d302eae'
down_revision = 'cab5f4843cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=False)
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    # ### end Alembic commands ###
